version: '3.8'

services:
  discord-mcp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=INFO
      - RATE_LIMIT_ENABLED=true
      - CACHE_TTL=300
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - discord-mcp-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - discord-mcp-network

  # 개발용 Redis Commander (선택사항)
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - discord-mcp-network
    profiles:
      - dev

volumes:
  redis_data:

networks:
  discord-mcp-network:
    driver: bridge
